### ISSUE TITLE
empty export

### ISSUE THREAD

**Issue by jeetiss** [millionjs/million#5] opened 2021-06-07 10:15 UTC
I create codesandbox with `million` and it fires with errors `million.m is not a function`, looks like problem in browser bundle

link: 
https://codesandbox.io/s/nervous-wright-k98xz?file=/src/index.js

**Comment by tejasag** [comment] 2021-06-07 11:54
Looks like some functions are not exported properly. We'll look into it. 
Meanwhile, you can use million with the unpkg source.
```html
<script src="https://unpkg.com/million"></script>
```
Then you can use the `Million` (mind the capital M) variable in your javascript

**Comment by aidenybai** [comment] 2021-06-07 16:30
Should be fixed by https://github.com/millionjs/million/commit/bfa67cd739b3bd1fe6a1c46baa179e8164f3169f

**Comment by jeetiss** [comment] 2021-06-07 18:56
@aidenybai export is still empty

**Comment by aidenybai** [comment] 2021-06-07 19:03
This is such a weird issue - I cannot reproduce in a prod/dev vite setup. Maybe it is an issue with parcel not recognizing that the esm build should be used?

**Comment by aidenybai** [comment] 2021-06-07 19:06
Forcing the import to be from `million/dist/million.esm` seems to work. Unsure if this is a codesandbox/parcel issue but this is a fix

**Comment by jeetiss** [comment] 2021-06-07 19:28
yep, thanks!

`parsel` forces [browser field](https://parceljs.org/module_resolution.html#package.json-%60browser%60-field) while resolves module

Why you don't use esm in browsers? like preact does

**Comment by aidenybai** [comment] 2021-06-07 19:31
The idea is generally to allow the user to just access it under `window.Million` - but esm sounds tempting

**Comment by aidenybai** [comment] 2021-06-07 21:42
UMD export by default in next release (esm, cjs, iife, amd supported)

**Closed by aidenybai** 2021-06-07 21:42 UTC
